# Generated by Django 4.1.4 on 2022-12-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.DateField(null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('position', models.CharField(choices=[('W', 'Worker'), ('C', 'Casher'), ('N', 'Cleaner')], default='W', max_length=1)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
