# Generated by Django 4.1.4 on 2022-12-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_alter_employee_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.DateField(null=True),
        ),
    ]
